---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3224070297-5CxDdoXPgKxvzEJW7r6o6wXzBXRMpMQsEcsnGZd
:access_token_secret: nyQiIuqBKxaLwmjH7pkqwfemO1Qkcv0JWDPjzN3V6A02a
